name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:

  unit-test-front:
    uses: ./.github/workflows/unit-test-front-end.yml

  unit-test-back:
    uses: ./.github/workflows/unit-test-back-end.yml