name: Setup Workflow

on:
  workflow_call:

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install back end dependencies
        run: |
          cd ./back-end-side
          npm ci
          npm audit --audit-level=critical
        working-directory: ./backend

      - name: Cache node_modules back end
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules/
          key: cache-node-modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Run Unit Test
        run: |
          cd ./back-end-side
          npm run test

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t thien3324/example-webapp:latest .