name: Unit Test Back End Workflow

on:
  workflow_call:

jobs:
  unit-test:
    name: unit test back end
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install back end dependencies
        run: |
          cd ./back-end-side
          npm ci
          npm audit --audit-level=critical

      - name: Run Unit Test
        run: |
          cd ./back-end-side
          npm run test